### ISSUE TITLE
Dont work anymore with Ele 3.6

### ISSUE THREAD

**Issue by digital-workshop** [dettogatto/elementor-super-cat#49]
With the new Update to 3.6 the plugin cause Elementor a "spinning wheel of death"
The Editor dont load anymore

**Comment by ekzig** [comment]
This should already be fixed? https://github.com/elementor/elementor/issues/18235

**Comment by digital-workshop** [comment]
it only happens when i activate "elementor-super-cat"

**Comment by encreinformatique** [comment]
In our case, it has been fixed by #18235 and the update to v3.6.1.

**Comment by ghost** [comment]
Elementor & Elementor pro up-to-date and still having the issue
